apiVersion: v1
kind: Service
metadata:
  name: node-todo-service
  namespace: node-todo
spec:
  type: NodePort
  selector:
    app: node-todo
    ports:
    - port: 80
      targetPort: 8000
      nodePort: 30007
